services:
  - type: web
    name: nexuscrm
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8000"
      - key: DEBUG
        value: "False"
      - key: PYDANTIC_SKIP_VALIDATION
        value: "1"
