"""Add Phase 3 marketing and analytics models

Revision ID: b43cc2803687
Revises: ff2e8ebaafce
Create Date: 2026-01-16 13:23:24.621641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43cc2803687'
down_revision = 'ff2e8ebaafce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_hits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('misses', sa.Integer(), nullable=True),
    sa.Column('hit_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_duration_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cache_hits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cache_hits_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_cache_hits_recorded_at'), ['recorded_at'], unique=False)

    op.create_table('performance_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('duration_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_logs_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('system_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cpu_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('memory_total', sa.BigInteger(), nullable=True),
    sa.Column('memory_available', sa.BigInteger(), nullable=True),
    sa.Column('memory_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('memory_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_total', sa.BigInteger(), nullable=True),
    sa.Column('disk_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('disk_free', sa.BigInteger(), nullable=True),
    sa.Column('network_sent', sa.BigInteger(), nullable=True),
    sa.Column('network_recv', sa.BigInteger(), nullable=True),
    sa.Column('process_memory', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('process_cpu', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_metrics_timestamp'), ['timestamp'], unique=False)

    op.create_table('content_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=100), nullable=True),
    sa.Column('metrics', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_posts_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('marketing_campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('channels', sa.Text(), nullable=False),
    sa.Column('message_templates', sa.Text(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('next_scheduled_run', sa.DateTime(), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('estimated_reach', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_campaigns_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('social_media_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('credentials', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_media_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_media_accounts_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('marketing_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marketing_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketing_messages_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_messages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketing_messages_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketing_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_messages_patient_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_messages_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_marketing_messages_campaign_id'))

    op.drop_table('marketing_messages')
    with op.batch_alter_table('social_media_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_media_accounts_clinic_id'))

    op.drop_table('social_media_accounts')
    with op.batch_alter_table('marketing_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketing_campaigns_clinic_id'))

    op.drop_table('marketing_campaigns')
    with op.batch_alter_table('content_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_posts_clinic_id'))

    op.drop_table('content_posts')
    with op.batch_alter_table('system_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_metrics_timestamp'))

    op.drop_table('system_metrics')
    with op.batch_alter_table('performance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_performance_logs_endpoint'))

    op.drop_table('performance_logs')
    with op.batch_alter_table('cache_hits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cache_hits_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_cache_hits_cache_key'))

    op.drop_table('cache_hits')
    # ### end Alembic commands ###
